---
version: '3'

services:
  base: &base
    image: pr8kerl/gobuilder:1.13
    volumes:
      - .:/go/src/github.com/pr8kerl/f5er
      - $HOME/.docker:/root/.docker
    working_dir: /go/src/github.com/pr8kerl/f5er
    entrypoint: make 

  f5er:
    build: .
    volumes:
      - .:/go/src/github.com/pr8kerl/f5er
      - $HOME/.f5:/root/.f5

  make:
    <<: *base
    environment:
      - GITHUB_TOKEN
      - TRAVIS_TAG

  goreleaser:
    <<: *base
    entrypoint: goreleaser
